server:
  port: 8081
## 数据源配置
spring:
  datasource: # 数据库的数据配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_enterprise?characterEncoding=UTF-8
    username: root
    password: 123456
    druid:
      initial-Size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      min-evictable-idle-runs-millis: 30000
      time-between-eviction-error-millis: 60000
      validation-query: select 1
      validation-query-timeout: 500
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # Spring 监控，利用aop 对指定接口的执行时间，jdbc数进行记录
      aop-patterns: "cn.ecust.dao.*"
      ########### 启用内置过滤器（第一个 stat必须，否则监控不到SQL）##########
      filters: stat,wall,log4j2
      filter:
        # 开启druid-datasource的状态监控
        stat:
          enabled: true
          db-type: mysql
          # 开启慢sql监控，超过2s 就认为是慢sql，记录到日志中
          log-slow-sql: true
          slow-sql-millis: 2000
        # 日志监控，使用slf4j 进行日志输出
        slf4j:
          enabled: true
          statement-log-error-enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
        ########## 配置WebStatFilter，用于采集web关联监控的数据 ##########
        web-stat-filter:
          enabled: true                   # 启动 StatFilter
          url-pattern: /*                 # 过滤所有url
          exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" # 排除一些不必要的url
          session-stat-enable: true       # 开启session统计功能
          session-stat-max-count: 1000    # session的最大个数,默认100
        ########## 配置StatViewServlet（监控页面），用于展示Druid的统计信息 ##########
        stat-view-servlet:
          enabled: true                   # 启用StatViewServlet
          url-pattern: /druid/*           # 访问内置监控页面的路径，内置监控页面的首页是/druid/index.html
          reset-enable: false             # 不允许清空统计数据,重新计算
          login-username: admin            # 配置监控页面访问密码
          login-password: 123456
        # allow: 127.0.0.1                # 允许访问的地址，如果allow没有配置或者为空，则允许所有访问
        # deny:                           # 拒绝访问的地址，deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝
  thymeleaf:
    cache: false

## mybatis 配置
mybatis:
  # 是否执行MyBatis xml配置文件的状态检查, 只是检查状态,默认false
  check-config-location: true
  mapper-locations: classpath:mybatis/mapper/*.xml # 扫描mybatis的实现dao接口*.xml文件
  #type-aliases-package: cn.ecust.web.entity #实体类取别名
  config-location: classpath:mybatis/mybatis-config.xml
logging:
  config: classpath:log4j2.xml